modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/StewStrong/Create-Interactive-Issues/issues"
license = "All Rights Reserved"

[[mods]]
modId = "create_interactive"
version = "${version}"
displayName = "Create Interactive"
authors = ["Tri0de"]
description = '''
Create made interactive!
'''
logoFile = "icon.png"

[[dependencies.create_interactive]]
modId = "forge"
mandatory = true
versionRange = "[40.1.69,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_interactive]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_interactive]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.create_interactive]]
modId = "create"
mandatory = true
versionRange = "[${create_forge_version},)"
ordering = "AFTER"
side = "BOTH"
