modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/StewStrong/Create-Interactive-Issues/issues"
license = "All Rights Reserved"

[[mods]]
modId = "create_interactive"
version = "${version}"
displayName = "Create: Interactive"
authors = ["Tri0de"]
description = '''
Create made interactive!
'''
logoFile = "icon.png"

[[dependencies.create_interactive]]
modId = "forge"
mandatory = true
versionRange = "[40.1.69,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_interactive]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_interactive]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.4.0,2.5.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.create_interactive]]
modId = "create"
mandatory = true
versionRange = "[6.0.7,)"
ordering = "AFTER"
side = "BOTH"
